<?php
function bakery_user_menu() {
    $items = array();
    $items['about'] = array(
        'title' => 'Hi There!',
        'page callback' => 'guestbook',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function comment_page() {
    return "<p> Weclome! </p>";
}

function guestbook() {
    return "<p> Welcome! </p>";
}

function bakery_user_user_login() {
    $_GET['destination'] = 'about';
}
